### ISSUE TITLE
www-authenticate not found on response of second request

### ISSUE THREAD

**Issue by rbartholomay** [gautamsi/ews-javascript-api-auth#12]
Hi,

I try to use the lib ews-javascript-api with this module using outlook365.

Everytime i get 'www-authenticate not found on response of second request´.   What must I do to resolve this?

**Comment by gautamsi** [comment]
are you sure you need NTLM auth?

**Comment by rbartholomay** [comment]
No, not sure. It‘s a corporate outlook365. When I try this without ntlm, I always get a 401. But the credentials work when I try outlook.office.de/owa/?realm=mydomain.de

**Comment by gautamsi** [comment]
you are using Germany O365. you do not need this library for auth with ews-javascript-api, basic auth is built in. use `WebCredential` class
