### ISSUE TITLE
Is this a global setting?

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api-auth#2]
I used to instanciate the exchnage service like:
```js
const exchange = new ews.ExchangeService(version);
exchange.Credentials = new ews.ExchangeCredentials(login, pass);
exchange.Url = new ews.Uri(externalServerUrl);
```
Since the app has to support multiple accounts, calling the code above multiple time with different user and password works fine.

If, however, I use the new ConfigurationApi for NLTM this will change the credentials of *all* previous instances of  ExchangeService, won't it?
```js
ews.ConfigurationApi.ConfigureXHR(new ewsAuth.ntlmAuthXhrApi(login, pass));
```

How can I use multiple Exchange Services, each with his own credentials (either Basic or NLTM)?

**Comment by gautamsi** [comment]
Authentication adapter is global.  Let me make a feature addition for this so that you can use it per instance

**Comment by gautamsi** [comment]
track [here](https://github.com/gautamsi/ews-javascript-api/issues/180)

**Comment by gautamsi** [comment]
closed referencing issue.

with 0.9 dev 7 You can now use this per instance of `ExchangeServiceBase` (`ExchangeService` and `AutodiscoverService`).

use `ConfigurationApi.ConfigureXHR` to configure this globally. when want to override modify using
```js
service.XHRApi = new ewsAuth.ntlmAuthXhrApi(credentials.userName, credentials.password)
```  
where `service` is `ExchangeService` or `AutodiscoverService`
