### ISSUE TITLE
Wrong default domain?

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api-auth#3]
Default domain set to `.` is probably wrong. Should empty string.
https://github.com/gautamsi/ews-javascript-api-auth/blob/master/src/ntlmAuthXhrApi.ts#L21

**Comment by gautamsi** [comment]
this is fixed in https://github.com/gautamsi/ews-javascript-api-auth/blob/ntlmv2/src/ntlmAuthXhrApi.ts#L21
