### ISSUE TITLE
How to use this? Missing Credentials?

### ISSUE THREAD

**Issue by nofear87** [gautamsi/ews-javascript-api-auth#4]
Can't get it work. I get always the message:

"credentials are required to make a service request",

```
var ews = require("ews-javascript-api");
var ewsAuth = require("ews-javascript-api-auth");
ews.ConfigurationApi.ConfigureXHR(new ewsAuth.ntlmAuthXhrApi(credentials.user, credentials.password));

var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
exch.Url = new ews.Uri("https://myexchange/ews/exchange.asmx");

exch.GetPasswordExpirationDate("my@mail.com").then(function(value){
    console.log(value);
},function(err){
    console.log(err);
});
```

**Comment by gautamsi** [comment]
just do a dummy  `exch.Credentials = new ews.ExchangeCredentials("fake it", "fake it");`

**Comment by nofear87** [comment]
Thank you! That was the missing part :-)

**Comment by allout58** [comment]
This doesn't work in TypeScript as the dummy ExchangeService class is marked as abstract. You have to create your own dummy class that extends ExchangeService class and use it as suggested above

**Comment by gautamsi** [comment]
Use WebCredentials which is not abstract
